# Generated by Django 4.2 on 2024-03-12 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fortytwotoken',
            old_name='secret_expires_at',
            new_name='expires_at',
        ),
        migrations.RemoveField(
            model_name='fortytwotoken',
            name='access_expires_at',
        ),
        migrations.RemoveField(
            model_name='fortytwotoken',
            name='access_token',
        ),
        migrations.RemoveField(
            model_name='fortytwotoken',
            name='login',
        ),
        migrations.RemoveField(
            model_name='fortytwotoken',
            name='refresh_token',
        ),
    ]
