# Generated by Django 4.2 on 2024-03-12 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_secret_expires_at_fortytwotoken_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fortytwotoken',
            name='expires_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
