# Generated by Django 4.2 on 2024-03-12 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_fortytwotoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fortytwotoken',
            name='expires_at',
            field=models.DateTimeField(),
        ),
    ]
