# Generated by Django 4.2 on 2024-03-15 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_fortytwotoken_expires_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='token_42',
        ),
        migrations.DeleteModel(
            name='FortyTwoToken',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
    ]
