# Generated by Django 4.2 on 2024-03-15 02:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FortyTwoToken',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('username', models.SlugField(max_length=24, unique=True)),
                ('pic', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('login_42', models.SlugField(blank=True, max_length=12, null=True, unique=True)),
                ('status', models.IntegerField(choices=[(0, 'Offline'), (1, 'Online'), (2, 'Playing')], default=0)),
                ('elo', models.IntegerField(default=0)),
                ('victories', models.IntegerField(default=0)),
                ('defeats', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token_42', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.fortytwotoken')),
            ],
        ),
    ]
