# Generated by Django 4.2 on 2024-04-06 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='permissions',
            field=models.OneToOneField(default=None, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='permissions_uid', to='app.userpermission'),
            preserve_default=False,
        ),
    ]
