# Generated by Django 4.2 on 2024-03-15 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FortyTwoToken',
            new_name='Pongtoken',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='token_42',
            new_name='pongtoken',
        ),
    ]
