# Generated by Django 4.2 on 2024-03-15 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_fortytwotoken_pongtoken_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='rank',
            field=models.IntegerField(choices=[(0, 'Unranked'), (1, 'Bronze'), (2, 'Silver'), (3, 'Gold'), (4, 'Platinium'), (5, 'Diamond'), (6, 'Elite'), (7, 'Champion'), (8, 'Unreal')], default=0),
        ),
    ]
