# Generated by Django 4.2 on 2024-04-06 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_player_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
