# Generated by Django 4.2 on 2024-04-06 03:07

import app.models.Player
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_invalidated_pongtoken_valid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.Player.rename_profile_picture),
        ),
    ]
