# Generated by Django 4.2 on 2024-04-06 03:38

import app.models.Player
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_player_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='password',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.Player.rename_profile_picture, validators=[app.models.Player.validate_profile_picture]),
        ),
    ]
