# Generated by Django 4.2 on 2024-04-06 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_player_password_alter_player_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='password',
            new_name='password_hash',
        ),
    ]
