# Generated by Django 4.2 on 2024-03-18 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_player_pongtoken_player_admin_pongtoken_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='status',
            field=models.TextField(choices=[('Offline', 'Offline'), ('Online', 'Online'), ('Playing', 'Playing')], default='Offline'),
        ),
    ]
