# Generated by Django 4.2 on 2024-04-06 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_player_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='password_hash',
            field=models.TextField(blank=True, null=True),
        ),
    ]
