# Generated by Django 4.2 on 2024-03-28 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_admin_player_operator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='pic',
            new_name='image',
        ),
    ]
