# Generated by Django 4.2 on 2024-04-06 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_player_password_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='password_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
