# Generated by Django 4.2 on 2024-04-03 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_player_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
