# Generated by Django 4.2 on 2024-04-07 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_elo_player_player_elo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='player_elo',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
