# Generated by Django 4.2 on 2024-04-07 02:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0013_alter_player_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('elo_min', models.IntegerField(blank=True, default=None, null=True)),
                ('elo_max', models.IntegerField(blank=True, default=None, null=True)),
                ('tournament_started_at', models.DateTimeField(blank=True, null=True)),
                ('tournament_ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='match',
            name='scheduled_at',
        ),
        migrations.AlterField(
            model_name='match',
            name='left_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_left_player_uid', to='app.player'),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_looser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_match_looser_uid', to='app.player'),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In progress', 'In progress'), ('Completed', 'Completed'), ('Abandoned', 'Abandoned')], default='Pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_match_winner_uid', to='app.player'),
        ),
        migrations.AlterField(
            model_name='match',
            name='right_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_right_player_uid', to='app.player'),
        ),
        migrations.AlterField(
            model_name='player',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_user_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TournamentRound',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('round_number', models.IntegerField(default=0)),
                ('round_started_at', models.DateTimeField(blank=True, null=True)),
                ('round_ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tournament', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournamentround_tournament_uid', to='app.tournament')),
            ],
        ),
        migrations.AddField(
            model_name='tournament',
            name='tournament_winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_tournament_winner_uid', to='app.player'),
        ),
        migrations.AddField(
            model_name='match',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_tournament_uid', to='app.tournament'),
        ),
        migrations.AddField(
            model_name='match',
            name='tournament_round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_tournament_round_uid', to='app.tournamentround'),
        ),
    ]
