# Generated by Django 4.2 on 2024-04-04 17:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_player_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('left_score', models.IntegerField(default=0)),
                ('left_elo', models.IntegerField(default=0)),
                ('left_delta', models.IntegerField(default=0)),
                ('right_score', models.IntegerField(default=0)),
                ('right_elo', models.IntegerField(default=0)),
                ('right_delta', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('left_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='left_player', to='app.player')),
                ('right_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='right_player', to='app.player')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.player')),
            ],
        ),
    ]
