# Generated by Django 4.2 on 2024-04-07 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_tournament_remove_match_scheduled_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='email_confirmed',
            field=models.BooleanField(default=0),
        ),
        migrations.DeleteModel(
            name='Pongtoken',
        ),
    ]
