# Generated by Django 4.2 on 2024-04-04 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='status',
            field=models.TextField(choices=[('Pending', 'Pending'), ('Scheduled', 'Scheduled'), ('In progress', 'In progress'), ('Completed', 'Completed'), ('Abandoned', 'Abandoned')], default='Pending'),
        ),
    ]
