# Generated by Django 4.2 on 2024-04-07 07:13

import app.models.EmailVerification
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_player_email_confirmed_delete_pongtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmationEmail',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('slug', models.SlugField(default=app.models.EmailVerification.generate_slug)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In progress', 'In progress'), ('Completed', 'Completed'), ('Abandoned', 'Abandoned')], default='Pending', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=app.models.EmailVerification.generate_expiration_timestamp, editable=False)),
            ],
        ),
        migrations.DeleteModel(
            name='UserPermission',
        ),
    ]
