# Generated by Django 4.2 on 2024-04-04 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_rename_left_elo_match_left_final_elo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='left_delta',
            new_name='lplayer_elo_delta',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='left_final_elo',
            new_name='lplayer_elo_final',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='left_initial_elo',
            new_name='lplayer_elo_initial',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='left_score',
            new_name='lplayer_score',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='right_delta',
            new_name='rplayer_delta',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='right_final_elo',
            new_name='rplayer_elo_final',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='right_initial_elo',
            new_name='rplayer_elo_initial',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='right_score',
            new_name='rplayer_score',
        ),
        migrations.RemoveField(
            model_name='match',
            name='left_player',
        ),
        migrations.RemoveField(
            model_name='match',
            name='right_player',
        ),
        migrations.AddField(
            model_name='match',
            name='lplayer_uid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lplayer_uid', to='app.player'),
        ),
        migrations.AddField(
            model_name='match',
            name='rplayer_uid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rplayer_uid', to='app.player'),
        ),
    ]
