# Generated by Django 4.2 on 2024-04-04 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_rename_left_delta_match_lplayer_elo_delta_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='rplayer_delta',
            new_name='rplayer_elo_delta',
        ),
    ]
