# Generated by Django 4.2 on 2024-04-04 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_rename_rplayer_delta_match_rplayer_elo_delta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='lplayer_elo_delta',
            new_name='left_player_elo_delta',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='lplayer_elo_final',
            new_name='left_player_elo_final',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='lplayer_elo_initial',
            new_name='left_player_elo_initial',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='lplayer_score',
            new_name='left_player_score',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='ended_at',
            new_name='match_ended_at',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='started_at',
            new_name='match_started_at',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='status',
            new_name='match_status',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='winner',
            new_name='match_winner',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='rplayer_elo_delta',
            new_name='right_player_elo_delta',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='rplayer_elo_final',
            new_name='right_player_elo_final',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='rplayer_elo_initial',
            new_name='right_player_elo_initial',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='rplayer_score',
            new_name='right_player_score',
        ),
        migrations.RemoveField(
            model_name='match',
            name='lplayer_uid',
        ),
        migrations.RemoveField(
            model_name='match',
            name='rplayer_uid',
        ),
        migrations.AddField(
            model_name='match',
            name='left_player_uid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='left_player_uid', to='app.player'),
        ),
        migrations.AddField(
            model_name='match',
            name='right_player_uid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='right_player_uid', to='app.player'),
        ),
    ]
