# Generated by Django 4.2 on 2024-04-07 11:04

import app.models.EmailVerification
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_remove_emailverification_email_sended_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='expires_at',
            field=models.DateTimeField(default=app.models.EmailVerification.generate_expiration_timestamp),
        ),
    ]
