# Generated by Django 4.2 on 2024-04-04 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_rename_left_player_uid_match_left_player_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='left_player_elo_delta',
        ),
        migrations.RemoveField(
            model_name='match',
            name='match_winner',
        ),
        migrations.RemoveField(
            model_name='match',
            name='right_player_elo_delta',
        ),
    ]
